const ACTION_TYPES = {
  LOGIN_REQUEST: 'auth/loginRequest',
  SIGN_UP_REQUEST: 'auth/signUpRequest',
  REFRESH_REQUEST: 'auth/refreshRequest',
  AUTH_SUCCESS: 'auth/success',
  AUTH_ERROR: 'auth/error',

  GET_MESSAGES_REQ: 'GET_MESSAGES_REQ',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_ERR: 'GET_MESSAGES_ERR',

  CREATE_MESSAGE_REQ: 'CREATE_MESSAGE_REQ',
  CREATE_MESSAGE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
  CREATE_MESSAGE_ERR: 'CREATE_MESSAGE_ERR',

  CLEAR_CHAT: 'CLEAR_CHAT',
};

export default ACTION_TYPES;
